INSERT INTO permissions (action, description, category) VALUES
('safetrack:status:report', 'Report own safety status', 'Status'),
('safetrack:status:readOwn', 'Read own safety status history', 'Status'),
('safetrack:status:read', 'Read any safety status', 'Status'),
('safetrack:employee:readOwn', 'Read own employee profile', 'Employee'),
('safetrack:employee:read', 'Read any employee', 'Employee'),
('safetrack:employee:create', 'Create a new employee', 'Employee'),
('safetrack:employee:update', 'Update employee details', 'Employee'),
('safetrack:employee:delete', 'Delete an employee', 'Employee'),
('safetrack:team:read', 'Read team information', 'Team'),
('safetrack:team:create', 'Create a team', 'Team'),
('safetrack:team:update', 'Update a team', 'Team'),
('safetrack:team:delete', 'Delete a team', 'Team'),
('safetrack:alert:send', 'Send alerts to employees', 'Alert'),
('safetrack:alert:read', 'Read sent alerts', 'Alert'),
('safetrack:organization:read', 'Read organization data', 'Organization'),
('safetrack:organization:update', 'Update organization settings', 'Organization'),
('safetrack:organization:delete', 'Delete organization data', 'Organization'),
('safetrack:userPermission:grant', 'Grant permissions to users', 'Admin'),
('safetrack:userPermission:revoke', 'Revoke permissions from users', 'Admin'),
('safetrack:userPermission:read', 'Read user permissions', 'Admin'),
('safetrack:role:assignSuperAdmin', 'Assign super-admin role', 'Admin'),
('safetrack:system:config', 'Modify system configuration', 'Admin')
ON CONFLICT (action) DO NOTHING;
